--
-- PostgreSQL database dump
--

-- Dumped from database version 17.3
-- Dumped by pg_dump version 17.2

-- Started on 2025-05-07 14:02:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 25351)
-- Name: Announcements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Announcements" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "AnnouncementDate" timestamp without time zone NOT NULL,
    "Description" text
);


ALTER TABLE public."Announcements" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 25395)
-- Name: AssignedItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AssignedItems" (
    "Id" uuid NOT NULL,
    "ItemNames" integer[] NOT NULL,
    "Description" character varying(500),
    "UserId" uuid NOT NULL
);


ALTER TABLE public."AssignedItems" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 25359)
-- Name: Departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Departments" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Departments" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25358)
-- Name: Departments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Departments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Departments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 25366)
-- Name: FoodLists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."FoodLists" (
    "Id" uuid NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "Description" character varying(200) NOT NULL
);


ALTER TABLE public."FoodLists" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 25373)
-- Name: Meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Meetings" (
    "Id" uuid NOT NULL,
    "Name" character varying(200),
    "Description" text,
    "MeetingDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL
);


ALTER TABLE public."Meetings" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 25380)
-- Name: Rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Rules" (
    "Id" uuid NOT NULL,
    "Description" character varying(2000) NOT NULL
);


ALTER TABLE public."Rules" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 25407)
-- Name: UserInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserInfo" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Birthday" date,
    "JobStartDate" date,
    "PhoneNumber" bigint,
    "JobTitle" character varying(100)
);


ALTER TABLE public."UserInfo" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 25387)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" uuid NOT NULL,
    "Name" character varying(100),
    "Email" character varying(150) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Active" boolean DEFAULT true NOT NULL,
    "Role" integer NOT NULL,
    "Department" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25346)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4898 (class 0 OID 25351)
-- Dependencies: 218
-- Data for Name: Announcements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Announcements" ("Id", "Name", "AnnouncementDate", "Description") FROM stdin;
01967c5d-cadb-7503-b41b-ef5e20bdb045	örnek duyuru	2025-04-28 18:27:00	<p>herkes işe gelsin</p><p><br></p>
\.


--
-- TOC entry 4905 (class 0 OID 25395)
-- Dependencies: 225
-- Data for Name: AssignedItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AssignedItems" ("Id", "ItemNames", "Description", "UserId") FROM stdin;
\.


--
-- TOC entry 4900 (class 0 OID 25359)
-- Dependencies: 220
-- Data for Name: Departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Departments" ("Id", "Name") FROM stdin;
\.


--
-- TOC entry 4901 (class 0 OID 25366)
-- Dependencies: 221
-- Data for Name: FoodLists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."FoodLists" ("Id", "ImageUrl", "Description") FROM stdin;
01967b90-af8a-7018-adf1-d09ee334db4e	WhatsApp Image 2025-04-22 at 10.46.11.jpeg	<p>28/04/255</p><p><br></p>
\.


--
-- TOC entry 4902 (class 0 OID 25373)
-- Dependencies: 222
-- Data for Name: Meetings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Meetings" ("Id", "Name", "Description", "MeetingDate", "EndDate") FROM stdin;
01967c5d-18f3-703f-b13a-52d611675bd7	toplantı	<p>önemli</p>	2025-04-29 18:26:00	2025-04-29 21:26:00
\.


--
-- TOC entry 4903 (class 0 OID 25380)
-- Dependencies: 223
-- Data for Name: Rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Rules" ("Id", "Description") FROM stdin;
01967c1d-24d8-7996-b18b-da07267304f4	\r\n\r\n\r\n\r\n\r\n\r\n<ul><li><span style="font-size: 1rem;">Şirketimizde tüm çalışanların belirlenen mesai saatlerine riayet ederek zamanında giriş çıkış yapmaları ve aksi durumları yöneticilerine bildirmeleri esastır.</span></li></ul><ul><li>Kendilerine verilen görevleri eksiksiz ve zamanında tamamlamak, iş akışının aksamamasını sağlar.</li></ul><ul><li>Şirket içi belge ve bilgilerin gizliliğine özen göstererek yalnızca yetkili kişilerle paylaşmak ve kişisel şifre ile erişim bilgilerini korumak büyük önem taşır.</li></ul><ul><li>İletişimde e-posta, telefon veya yüz yüze görüşmelerde saygılı, açık ve nazik bir dil kullanmak; kritik konuları yazılı olarak teyit etmek yanlış anlamaları önler.</li></ul><ul><li>Ortak kullanım alanlarını —mutfak, toplantı odası, dinlenme alanı vb.— temiz ve düzenli bırakmak, hem hijyen hem de profesyonellik açısından herkese kolaylık sağlar.</li></ul><ul><li>İş sağlığı ve güvenliği ekipmanlarını doğru şekilde kullanmak ve olası tehlikeleri derhal ilgili birimlere bildirmek, çalışma ortamımızın güvenliği için elzemdir.</li></ul><ul><li>Son olarak, ekip arkadaşlarıyla iş birliği içinde çalışmak, ihtiyaç duyulduğunda yardım teklif etmek ve bilgi paylaşımını teşvik etmek; ortak hedeflere odaklanarak şirketimizin başarısına katkı sağlamayı mümkün kılar.</li></ul>
\.


--
-- TOC entry 4906 (class 0 OID 25407)
-- Dependencies: 226
-- Data for Name: UserInfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserInfo" ("Id", "UserId", "Birthday", "JobStartDate", "PhoneNumber", "JobTitle") FROM stdin;
0196a5a1-9afd-774d-ab18-a8075cdda416	0196a5a1-9af8-7263-9771-3a94cd377dc3	2025-05-06	2025-05-06	0	test
\.


--
-- TOC entry 4904 (class 0 OID 25387)
-- Dependencies: 224
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "Password", "Active", "Role", "Department") FROM stdin;
0196a5a1-9af8-7263-9771-3a94cd377dc3	test	test@gmail.com	9ydHsxjZExCyrb/b5LTGpveqx6NL57LAjV2jpbZ7Wc4=:Yy//U8gSrZaQ1+Is/BNFcw==	t	1	1
\.


--
-- TOC entry 4897 (class 0 OID 25346)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250428083557_WiserSenseContext	9.0.3
20250428142208_mig_user_birthday_fix	9.0.3
\.


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 219
-- Name: Departments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Departments_Id_seq"', 1, false);


--
-- TOC entry 4731 (class 2606 OID 25357)
-- Name: Announcements PK_Announcements; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Announcements"
    ADD CONSTRAINT "PK_Announcements" PRIMARY KEY ("Id");


--
-- TOC entry 4745 (class 2606 OID 25401)
-- Name: AssignedItems PK_AssignedItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AssignedItems"
    ADD CONSTRAINT "PK_AssignedItems" PRIMARY KEY ("Id");


--
-- TOC entry 4733 (class 2606 OID 25365)
-- Name: Departments PK_Departments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "PK_Departments" PRIMARY KEY ("Id");


--
-- TOC entry 4735 (class 2606 OID 25372)
-- Name: FoodLists PK_FoodLists; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FoodLists"
    ADD CONSTRAINT "PK_FoodLists" PRIMARY KEY ("Id");


--
-- TOC entry 4737 (class 2606 OID 25379)
-- Name: Meetings PK_Meetings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meetings"
    ADD CONSTRAINT "PK_Meetings" PRIMARY KEY ("Id");


--
-- TOC entry 4739 (class 2606 OID 25386)
-- Name: Rules PK_Rules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rules"
    ADD CONSTRAINT "PK_Rules" PRIMARY KEY ("Id");


--
-- TOC entry 4749 (class 2606 OID 25411)
-- Name: UserInfo PK_UserInfo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfo"
    ADD CONSTRAINT "PK_UserInfo" PRIMARY KEY ("Id");


--
-- TOC entry 4742 (class 2606 OID 25394)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4729 (class 2606 OID 25350)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4743 (class 1259 OID 25417)
-- Name: IX_AssignedItems_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AssignedItems_UserId" ON public."AssignedItems" USING btree ("UserId");


--
-- TOC entry 4746 (class 1259 OID 25418)
-- Name: IX_UserInfo_PhoneNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UserInfo_PhoneNumber" ON public."UserInfo" USING btree ("PhoneNumber") WHERE ("PhoneNumber" IS NOT NULL);


--
-- TOC entry 4747 (class 1259 OID 25419)
-- Name: IX_UserInfo_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UserInfo_UserId" ON public."UserInfo" USING btree ("UserId");


--
-- TOC entry 4740 (class 1259 OID 25420)
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- TOC entry 4750 (class 2606 OID 25402)
-- Name: AssignedItems FK_AssignedItems_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AssignedItems"
    ADD CONSTRAINT "FK_AssignedItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4751 (class 2606 OID 25412)
-- Name: UserInfo FK_UserInfo_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfo"
    ADD CONSTRAINT "FK_UserInfo_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


-- Completed on 2025-05-07 14:02:27

--
-- PostgreSQL database dump complete
--

